version: "3"
networks:
  langflow:

services:
  backend:
    build:
      context: ./backend
    ports:
      - "7860:7860"
    networks:
      - langflow
    command:
      - langflow
      - run
      - --host
      - 0.0.0.0
      - --backend-only
      - --log-level
      - info
      - --workers
      - "1"
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:7860
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - langflow
