name: ragstack-lint

on:
  push:
    branches: [ragstack-main]
    paths:
      - "ragstack/tests/**"
  pull_request:
    paths:
      - "ragstack/poetry.lock"
      - "ragstack/pyproject.toml"
      - "ragstack/tests/**"

env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_caching"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('ragstack/poetry.lock') }}
      - name: Install Python dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install
        working-directory: ragstack/
      - name: Get .mypy_cache to speed up mypy
        uses: actions/cache@v4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: "2"
        with:
          path: |
            ./ragstack/.mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('ragstack/pyproject.toml') }}
      - name: Lint check
        run: |
          make lint
        working-directory: ragstack/
